import { FaRobot, FaFileAlt, FaChartLine } from "react-icons/fa";

function Features() {
  const features = [
    {
      icon: <FaRobot size={40} className="text-cyan-400" />,
      title: "AI Mock Interview",
      desc: "Practice real interview questions generated by AI.",
    },
    {
      icon: <FaFileAlt size={40} className="text-cyan-400" />,
      title: "Resume Analyzer",
      desc: "Upload your resume and receive personalized feedback.",
    },
    {
      icon: <FaChartLine size={40} className="text-cyan-400" />,
      title: "Performance Dashboard",
      desc: "Track your interview scores and improve over time.",
    },
  ];

  return (
    <section className="py-20 px-10 bg-slate-900">
      <h2 className="text-4xl font-bold text-center mb-12">
        Why Choose PlacementPilot AI?
      </h2>

      <div className="grid md:grid-cols-3 gap-8">
        {features.map((feature, index) => (
          <div
            key={index}
            className="bg-slate-800 rounded-2xl p-8 hover:scale-105 transition duration-300"
          >
            {feature.icon}

            <h3 className="text-2xl font-bold mt-6">
              {feature.title}
            </h3>

            <p className="text-gray-400 mt-4">
              {feature.desc}
            </p>
          </div>
        ))}
      </div>
    </section>
  );
}

export default Features;